import LayoutComponents from "@/components/LayoutComponents";
import SVGs from "@/components/SVGs";
import { cn } from "@/lib/utils";
import Providers, { ThemeProvider } from "@/providers/Providers";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
  src: "../../assets/fonts/Bahij_TheSansArabic-Plain.ttf",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="ar" suppressHydrationWarning>
        <head />
        <body className={cn("min-h-screen bg-background font-sans antialiased", inter.variable)}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <>
              <SVGs />
              <LayoutComponents />
              {children}
            </>
          </ThemeProvider>
        </body>
      </html>
    </Providers>
  );
}
